# Generated by Django 4.2 on 2023-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_match_away_team_logo_match_flag_match_home_team_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingTipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('odd_value', models.FloatField()),
                ('game_prediction', models.CharField(max_length=255)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('sport_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('match_id', models.IntegerField()),
                ('flag', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('home_team_logo', models.URLField()),
                ('away_team_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('winner_team_name', models.CharField(max_length=255)),
                ('home_percent', models.FloatField()),
                ('draw_percent', models.FloatField()),
                ('away_percent', models.FloatField()),
                ('advice', models.CharField(max_length=255)),
                ('home_form', models.CharField(max_length=255)),
                ('home_attack', models.CharField(max_length=255)),
                ('home_def', models.CharField(max_length=255)),
                ('home_goals_total', models.IntegerField()),
                ('home_goals_average', models.FloatField()),
                ('home_goals_against_total', models.IntegerField()),
                ('home_goals_against_average', models.FloatField()),
                ('away_form', models.CharField(max_length=255)),
                ('away_attack', models.CharField(max_length=255)),
                ('away_def', models.CharField(max_length=255)),
                ('away_goals_total', models.IntegerField()),
                ('away_goals_average', models.FloatField()),
                ('away_goals_against_total', models.IntegerField()),
                ('away_goals_against_average', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
